java_test(
    name = "tests",
    size = "small",
    srcs = glob(["java/com/talios/bazeltest/*.java"]),
    deps = [
        "@hamcrest//jar",
        "@junit//jar",
    ],
    #    runtime_deps = [
    #        "//src/main:bazeltest_impl",
    #    ],
)
