maven_jar(name = "guava",            artifact = "com.google.guava:guava:19.0")
maven_jar(name = "dagger",           artifact = "com.google.dagger:dagger:2.0")
maven_jar(name = "dagger_compiler",  artifact = "com.google.dagger:dagger-compiler:2.0")
maven_jar(name = "dagger_producers", artifact = "com.google.dagger:dagger-producers:2.0-beta")
maven_jar(name = "javax_inject",     artifact = "javax.inject:javax.inject:1")
maven_jar(name = "javaslang",        artifact = "com.javaslang:javaslang:1.2.0")
maven_jar(name = "javapoet",         artifact = "com.squareup:javapoet:1.0.0")
